#!/bin/bash
basename=${1%.inp}

IFS=' ' read -r -a array <<< `head -n 3 $1 | tail -n 1`
procs=${array[2]}

IFS=' ' read -r -a array <<< `tail -n 1 $1`
charge=${array[1]}
xyz=${array[3]}

echo -e "\$embedding\n   interface=orca\n\$end" > xtb.input

pointcharges=`grep "%pointcharges" $1 | awk '{print $2}' | tr -d '"'`
cp $pointcharges ${basename}.pcharge

xtb --grad -c $charge -P $procs --namespace $basename --input xtb.input $xyz 2>err >out

engrad=${basename}.engrad

echo -e "# The current total energy in Eh\n" > $engrad
IFS=' ' read -r -a array <<< `head -n 2 ${basename}.energy | tail -n 1`
energy=${array[1]}
echo $energy >> $engrad

echo -e "# The current gradient in Eh/bohr\n" >> $engrad
natoms=`head -n 1 $xyz`
tail -n$(($natoms+1)) ${basename}.gradient | head -n$natoms | awk '{printf("%22.12f\n%22.12f\n%22.12f\n", $1, $2, $3)}' >> $engrad

pcgrad=$basename.pcgrad
cp $pcgrad tmp
head -n 1 ${basename}.pcharge > $pcgrad
awk '{printf("%17.12f\n%17.12f\n%17.12f\n", $1, $2, $3)}' tmp >> $pcgrad

rm tmp ${basename}.charges ${basename}.wbo ${basename}.xtbrestart ${basename}.energy ${basename}.gradient ${basename}.pcharge
